esphome:
  name: aoycocr_plug_5
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "SSID"
  password: "PASSWORD"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Aoycocr Plug 5 Fallback Hotspot"
    password: "PASSWORD"

captive_portal:

# Enable logging
logger:

web_server:
  port: 80
  
# Enable Home Assistant API
api:
  #If using without HomeAssistant un-comment line below or plug will reboot every 15 mins.
  #reboot_timeout: 0s

ota:

time:
  - platform: homeassistant
    id: homeassistant_time
    
binary_sensor:
  - platform: gpio
    name: Aoycocr_Plug_5_Button
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: relay
  - platform: status
    name: Aoycocr_Plug_5_Status

switch:
  - platform: gpio
    id: relay
    name: Aoycocr_Plug_5_Relay
    icon: mdi:power-socket-uk
    restore_mode: ALWAYS_ON
    pin: GPIO15
    on_turn_on:
      - switch.turn_on: blue_led
    on_turn_off:
      - switch.turn_off: blue_led

  - platform: gpio
    id: blue_led
    name: Aoycocr_Plug_5_LED_Blue
    icon: mdi:led-on
    restore_mode: ALWAYS_ON
    pin: 
      number: GPIO02
      inverted: True

sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO05
    cf1_pin: GPIO14
    current_resistor: 0.00221
    voltage_divider: 955
    current:
      name: Aoycocr_Plug_5_Amperage
      icon: mdi:current-ac
      unit_of_measurement: A
    voltage:
      name: Aoycocr_Plug_5_Voltage
      icon: mdi:flash-circle
      unit_of_measurement: V
    power:
      name: Aoycocr_Plug_5_Wattage
      icon: mdi:flash-outline
      unit_of_measurement: W
      id: Aoycocr_Plug_5_Wattage
    change_mode_every: 8
    update_interval: 10s

  - platform: total_daily_energy
    name: Aoycocr_Plug_5_Total_Daily_Energy
    icon: mdi:circle-slice-3
    power_id: Aoycocr_Plug_5_Wattage
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh
      
# Extra sensor to keep track of plug uptime
  - platform: uptime
    name: Aoycocr_Plug_5_Uptime_Sensor

  - platform: wifi_signal
    name: Aoycocr_Plug_5_Wi-Fi_Signal
    update_interval: 60s
